// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6RCpWvmq035XtjjOm84Y4WJDY3ascLpg',
    appId: '1:680917793551:android:54811ef0a961da589c9c7a',
    messagingSenderId: '680917793551',
    projectId: 'final-9b5bd',
    storageBucket: 'final-9b5bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEQjX8rWVpy_rNtHJbpu1j5oS_vxD5ijE',
    appId: '1:680917793551:ios:776184ac30e014cc9c9c7a',
    messagingSenderId: '680917793551',
    projectId: 'final-9b5bd',
    storageBucket: 'final-9b5bd.appspot.com',
    iosClientId: '680917793551-kr3fm4jpgfks6umtd5901r395rtsd5i4.apps.googleusercontent.com',
    iosBundleId: 'com.example.finalRe',
  );
}
